version: '3'

services:
    nginx:
        build:
            context: .docker/nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/dico
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .docker/nginx/sites/:/etc/nginx/sites-available
            - .docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build:
            context: .docker/php-fpm
        restart: unless-stopped
        volumes:
            - ./:/var/www/dico
        working_dir: "/var/www/dico"
        networks:
            - app-network

    db:
        build:
            context: .docker/db
        restart: unless-stopped
        volumes:
            - .docker/dbdata:/var/lib/mysql
            - .docker/db/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_DATABASE=ngyemboon
            - MYSQL_ROOT_PASSWORD=Secur1ty
        networks:
            - app-network

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - app-network
        links:
            - db
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
