<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */

declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\EntryHandler::class => App\Handler\EntryHandlerFactory::class,
        ],
        'invokables' => [
            App\Handler\IndexHandler::class => App\Handler\IndexHandler::class,
        ],
    ],
];
